services:
  web:
    build:
      dockerfile: ./.docker/go/Dockerfile
      context: ./
    ports:
      - 80:80
    volumes:
      - ./:/app
  redis:
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: "--save 60 1000 --appendonly yes"
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data
    restart: always
