name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Generate env prod file
        run: echo "${{ secrets.ENV_PROD }}" > .env.prod
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install frontend dependencies
        run: npm install
      - name: Build frontend
        run: npm run prod
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        run: docker build . -t dorianneto/burn-secret-web -f ./.docker/go/Dockerfile --platform linux/amd64
      - name: Push docker
        run: docker push dorianneto/burn-secret-web:latest
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull docker image
        run: docker pull dorianneto/burn-secret-web:latest
      - name: Remove current container
        run: docker rm -f burn-secret-web-container
      - name: Runs container
        run: docker run -d -p 80:80 -e APP_ENV=prod --name burn-secret-web-container dorianneto/burn-secret-web
